ARG DOTNETCORE_VERSION

FROM mcr.microsoft.com/dotnet/core/aspnet:$DOTNETCORE_VERSION-alpine

WORKDIR /app

RUN apk add bash

ONBUILD COPY --from=builder /usr/local/app-name /usr/local
ONBUILD COPY --from=builder /app .

CMD dotnet $(cat /usr/local/app-name)
