ARG DOTNETCORE_VERSION

FROM mcr.microsoft.com/dotnet/core/sdk:$DOTNETCORE_VERSION

WORKDIR /src

COPY builder.sh /usr/local/bin/builder.sh

ONBUILD COPY . .

ONBUILD ARG __NETCORE_CSPROJECTFILE
ONBUILD ARG __NETCORE_FINALDLLNAME
ONBUILD ENV __NETCORE_CSPROJECTFILE=${__NETCORE_CSPROJECTFILE} \
  __NETCORE_FINALDLLNAME=${__NETCORE_FINALDLLNAME}

ONBUILD RUN chmod +x /usr/local/bin/builder.sh && /usr/local/bin/builder.sh
